"""add skill_gap to analyses

Revision ID: a062e33cc4a1
Revises: cf58d77d2c73
Create Date: 2026-09-01 16:29:27.226106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a062e33cc4a1'
down_revision: Union[str, Sequence[str], None] = 'cf58d77d2c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('skill_gap', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'skill_gap')
    # ### end Alembic commands ###
