"""add parsed_resume to analyses

Revision ID: cf58d77d2c73
Revises: 4084b01e6e4f
Create Date: 2026-09-01 14:34:11.510895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf58d77d2c73'
down_revision: Union[str, Sequence[str], None] = '4084b01e6e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('parsed_resume', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'parsed_resume')
    # ### end Alembic commands ###
