"""add keyword_score and semantic_score to analyses

Revision ID: f58dffcf316f
Revises: a062e33cc4a1
Create Date: 2026-09-01 16:56:41.264108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58dffcf316f'
down_revision: Union[str, Sequence[str], None] = 'a062e33cc4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('keyword_score', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('semantic_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'semantic_score')
    op.drop_column('analyses', 'keyword_score')
    # ### end Alembic commands ###
